# Generated by Django 3.2.12 on 2022-11-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
